core/urls.py
from django.urls import path
from .views import HomePage
from . import views

app_name = "core"
urlpatterns = [
    path('', HomePage.as_view(), name="cat-home"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register, name="register"),
    path('vote/<int:id>/', views.vote, name="vote"),
    path('<str:slug>/', views.detail, name="detail")
]

pdpolls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from .mailing import send_ses_mail
from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def email_user(self, *args, **kwargs):
        """
        subject: first argument\n
        message: second argument
        """
        send_ses_mail(
            '{}'.format(args[0]), # Subject
            '{}'.format(args[1]), # Message
            self.email,
            )


    def __str__(self):
        return self.email


class Category(models.Model):
    name = models.CharField(max_length=50)
    order = models.PositiveSmallIntegerField(unique=True)
    slug = models.CharField(max_length=50, blank=True, unique=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs): # new
        if not self.slug:
            self.slug = '-'.join(str(self.name).lower().split())
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class VoteItem(models.Model):
    name = models.CharField(max_length=50)
    # TODO: image = models.ImageField(upload_to=None)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name


class Profile(models.Model):

    person = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=True)
    first_name = models.CharField("First Name", blank=True, max_length=20)
    last_name = models.CharField("Last Name", blank=True, max_length=20)
    votes = models.ManyToManyField(VoteItem)
    categories_voted = models.ManyToManyField(Category)

    def get_full_name(self):
        return f"{self.first_name.capitalize()} {self.last_name.capitalize()}"
        
    def __str__(self):
        return self.person.email

@receiver(post_save, sender=CustomUser)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(person=instance)
    instance.profile.save()

core/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.db import models

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)



class SignUpForm(CustomUserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Please, provide a valid email address.')

    class Meta:
        model = CustomUser
        fields = ('email')

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.views.generic import TemplateView
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
import random
import string

from .models import Category, VoteItem, Profile

class HomePage(TemplateView):
    template_name = "core/categories.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({ "categories": Category.objects.all() })
        return context
    


# Non View Functions
def send_password(user, password, request):
    message = render_to_string('core/password_sent_email.txt', {
        'password': password,
        'domain': get_current_site(request).domain
        })
    user.email_user("Password Mail", message)


def random_string_digits(string_length=6):
    """Generate a random string of letters and digits """
    letters_and_digits = string.ascii_letters + string.digits
    return ''.join(random.choice(letters_and_digits) for i in range(string_length))



def detail(request, slug):
    context = {}
    category = get_object_or_404(Category, slug=slug)
    category_list = Category.objects.order_by('id')
    p = Paginator(category_list, 1)
    for i in p.page_range:
        if category in p.page(i).object_list:
            page = p.page(i)
            if page.has_next():
                next_slug = p.page(i+1).object_list[0].slug
                context["next_slug"] = next_slug
            if page.has_previous():
                prev_slug = p.page(i-1).object_list[0].slug
                context["prev_slug"] = prev_slug
            break
    context.update({
        "category": category,
        "page": page,
    })
    return render(request, 'core/detail.html', context)


def login_view(request):
    alert = None
    if request.user.is_authenticated:
        return redirect("/")
    if request.method == "POST":
        email = request.POST.get("login-email")
        password = request.POST.get("login-password")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            alert = {
                'text': 'Invalid Login Details!',
                'class': 'danger'
            }
    context = {
        "login": True,
        "register": False,
        "alert": alert
    }
    return render(request, 'core/auth.html', context)


def register(request):
    alert = None
    User = get_user_model()
    if request.method == "POST":
        email = request.POST.get("email")
        if User.objects.filter(email=email).exists():
            context = {
                "login": False,
                "register": True,
                "alert": {
                    'text': 'Email exists!',
                    'class': 'danger'
                }
            }
            return render(request, 'core/auth.html', context)

        password = f"lmu-{random_string_digits()}"
        try:
            u = User.objects.create_user(email=email, password=password)
        except Exception:
            return redirect("/login")
        u.save()
        send_password(u, password, request)
        alert = {
            'text': 'The Password has been sent to your email!',
            'class': 'success'
        }

    context = {
        "login": False,
        "register": True,
        "alert": alert
    }
    return render(request, 'core/auth.html', context)


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("/")

@login_required
def vote(request, id):
    if request.method == "POST":
        user = request.user
        profile = get_object_or_404(Profile, person=user)
        item = get_object_or_404(VoteItem, id=id)
        if user.is_staff:
            raise Http404("No admin can vote")
        if item.category in profile.categories_voted.all():
            raise Http404("No more votes for this category")
        profile.votes.add(item)
        profile.categories_voted.add(item.category)
        profile.save()
        return redirect("/%s"%item.category.slug)
    else:
        raise Http404("Invalid Vote Request Type")

core/templates/_topnav.html
<nav
  class="d-flex py-4 bg-white shadow text-right text-dark px-2 px-md-3 px-lg-5"
>
  <a class="mr-auto" href="{% url 'core:cat-home' %}">PD Polls</a>
  {% if request.user.is_authenticated %}
  <!-- Logged in -->
  {% if request.user.is_staff %}
  <a href="/admin" class="d-inline-block mx-2">Dashboard</a>
  {% else %}
  <span class="d-inline-block mx-2">Welcome!!</span>
  {% endif %}
  <span class="d-inline-block">
    <a href="javascript: document.getElementById('logout').submit()">Logout</a>
    <form
      method="post"
      id="logout"
      action="{% url 'core:logout' %}"
      class="d-none"
    >
      {% csrf_token %}
    </form>
  </span>
  {% else %}
  <a href="{% url 'core:login' %}" class="d-block">Login</a>
  {% endif %}
</nav>

core/templates/core/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    {% block extrastyles %}{% endblock extrastyles %}
    <title>{% block title%}{% endblock title%}</title>
  </head>
  <body>
    {% block body %}{% endblock body %}
    <div
      class="w-100 text-right text-muted mt-n5 p-3 copyright"
      style="font-size: 0.75rem"
    >
      <hr class="d-inline-block w-50 mr-2" style="vertical-align: middle" />
      Developed by
      <a target="_blank" href="http://jbritz.tech" class="my-name"
        >Ajibola Ojo</a
      >
    </div>
    {% block extrascripts %}{% endblock extrascripts %}
    <style>
      .display-5 {
        font-size: 3rem;
      }
      .my-name {
        border-bottom: 2px dotted;
        color: #575a89;
      }
      .my-name:hover {
        color: purple;
        text-decoration: none;
      }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.all.js"></script>
  </body>
</html>

core/templates/core/categories.html
{% extends "core/base.html" %} {% block title %}Categories{% endblock title %}
{% block extrastyles %}<link
  href="https://fonts.googleapis.com/css?family=Nunito:600&display=swap"
  rel="stylesheet"
/>{% endblock extrastyles %} {% block body%} {% include "_topnav.html" %}
<div class="bg-white w-100">
  <div
    class="cat-head p-5 w-100 text-center"
    style="
      background-color: #f1f1f1;
      font-family: 'Nunito', sans-serif;
      color: #602020;
      border-left: solid 15px #602020;
    "
  >
    <span class="display-5 text-center"> PureDev Categories </span>
  </div>
  <div class="text-center w-75 mx-auto py-5" style="max-width: 880px">
    {% for category in categories %}
    <a
      href="{% url 'core:detail' slug=category.slug %}"
      class="m-1 m-md-2 btn cat-link"
      >{{category}}</a
    >
    {% empty %}
    <h3>No Categories yet</h3>
    {% endfor %}
  </div>
</div>
<div class="footer"></div>
<style>
  .cat-link {
    border: dashed 1px #999;
    color: #999;
  }
  .cat-link:hover {
    color: #a0616a;
    border-color: #a0616a;
    box-shadow: none;
  }
  .cat-link:active {
    box-shadow: none;
  }
</style>
{% endblock body%}

core/templates/core/detail.html
{% extends "core/base.html" %}
<!--  -->
{% block title %} {{category.name}} | PureDev {% endblock title %}
<!--  -->
{% block extrastyles %}
<link
  href="https://fonts.googleapis.com/css?family=Nunito:600&display=swap"
  rel="stylesheet"
/>
{% endblock extrastyles %} {% block body%}
<!-- Nav -->
{% include "_topnav.html" %}
<div class="bg-light w-100">
  <div
    class="cat-head p-5 w-100 shadow-s"
    style="
      background-color: #f1f1f1;
      font-family: 'Nunito', sans-serif;
      color: #602020;
      border-left: solid 15px black;
    "
  >
    <span class="display-5 px-5"> {{category.name}} </span>
  </div>

  <div class="card-display w-100 row py-5">
    {% for voteitem in category.items.all %}
    <div class="card col-2 mx-auto">
      <span href="#">{{voteitem.name}}</span>
      <div class="card-body">
        <div class="d-flex">
          <a
            href="javascript: document.getElementById('vote{{voteitem.id}}').submit()"
            >vote</a
          >
          {% if voteitem in request.user.profile.votes.all%}
          <span class="d-block"> Voted 👌 </span>
          {% endif %}
        </div>
        <form
          method="post"
          class="d-none"
          action="{% url 'core:vote' id=voteitem.id %}"
          id="vote{{voteitem.id}}"
        >
          {% csrf_token %}
        </form>
      </div>
    </div>
    {% empty %}
    <h5>No Item In this category</h5>
    {% endfor %}
  </div>

  <div class="cat-nav text-center pb-5">
    {% if page.has_previous %}
    <a class="cat-nav-btn" href="{% url 'core:detail' slug=prev_slug %}"
      >Previous Category</a
    >
    {% else %}
    <a class="cat-nav-btn" href="{% url 'core:cat-home' %}"
      >Back to Categories page</a
    >
    {% endif %} {% if page.has_next %}
    <a class="cat-nav-btn" href="{% url 'core:detail' slug=next_slug %}"
      >Next Category</a
    >
    {% else %}
    <a class="cat-nav-btn" href="{% url 'core:cat-home' %}"
      >Back to Categories page</a
    >
    {% endif %}
  </div>
</div>
<style>
  .cat-nav-btn {
    padding: 10px;
    margin-left: 5px;
    margin-right: 5px;
    border: 1px solid black;
  }
</style>

{% endblock body%}

core/templates/core/home.html
{% extends 'core/base.html' %} {% block body %}
<h1>Pd Polls Base Page!</h1>
{% endblock %}

core/templates/core/new_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    {% block styles %} {% endblock %}
    <title>PdPolls</title>
  </head>
  <body>
    {% block body %} {% endblock %} {% block scripts %} {% endblock %}
    <!-- Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

core/templates/core/password_sent_email.html
<div>
  Hi, Your password for https://{{ domain }} is: <strong>{{ password }}</strong>
</div>